server {
    listen 80;

    location /its-resto/ {
        alias /usr/share/nginx/html/;
        index index.html index.htm;

        try_files $uri $uri/ /its-resto/index.html;
    }

    location / {
        return 301 /its-resto/;
    }

    error_page 404 /index.html;
}