server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Menambahkan pengecekan di berbagai kemungkinan path folder (berjaga-jaga jika Vite melempar file ke subfolder atau Apache mengubah path secara tidak terduga)
        try_files $uri $uri/ /its-resto$uri /assets$uri /index.html;
    }
}